# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cv_builder_db
  pool: 5
  username: root
  password: asdfgh
  

fast_mode:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: cv_builder_db
  pool: 5
  username: root
  password: asdfgh
  

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: cv_builder_db
  pool: 5
  username: root
  password: asdfgh
#  socket: /var/run/mysqld/mysqld.sock
  port: 5432
  host: localhost
